name: build_and_push.yml
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./src/book-rag-backend
    steps:
      - uses: actions/checkout@v4
      - name: Get repository owner
        run: |
          echo "OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Artifactory login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/book-rag-backend
          file: ./src/book-rag-backend/Dockerfile
          push: true
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check image
        run: docker images | grep ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend

  push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./src/book-rag-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Get repository owner
        run: |
          echo "OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Artifactory login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/book-rag-frontend
          file: ./src/book-rag-frontend/Dockerfile
          push: true
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check image
        run: docker images | grep ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend
