name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/book-rag-backend

    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Run unit tests
        run: uv run pytest tests/ --cov=book_rag_backend --cov-report=term --cov-config=.coveragerc

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test-backend
    defaults:
      run:
        working-directory: ./src/book-rag-backend
    steps:
      - uses: actions/checkout@v4
      - name: Get repository owner
        run: |
          echo "OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Artifactory login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/book-rag-backend
          file: ./src/book-rag-backend/Dockerfile
          push: true
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check image
        run: docker images | grep ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-backend

  test-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: ./src/book-rag-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage -- --run

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage-report
          path: ./src/book-rag-frontend/coverage/
          retention-days: 7

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test-frontend
    defaults:
      run:
        working-directory: ./src/book-rag-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Get repository owner
        run: |
          echo "OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Artifactory login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/book-rag-frontend
          file: ./src/book-rag-frontend/Dockerfile
          push: true
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check image
        run: docker images | grep ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ github.event.repository.name }}/book-rag-frontend
